# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Iddqx7Vw969TIJska_f3uJjbTTip_bV
"""

import math

# Hard-coded dataset
data = [
    (0.22, 0.33),
    (0.45, 0.76),
    (0.73, 0.39),
    (0.25, 0.35),
    (0.51, 0.69),
    (0.69, 0.42),
    (0.41, 0.49),
    (0.15, 0.29),
    (0.81, 0.32),
    (0.50, 0.88),
    (0.23, 0.31),
    (0.77, 0.30),
    (0.56, 0.75),
    (0.11, 0.38),
    (0.81, 0.33),
    (0.59, 0.77),
    (0.10, 0.89),
    (0.55, 0.09),
    (0.75, 0.35),
    (0.44, 0.55)
]

# Read 6 input values
values = [float(input()) for _ in range(6)]

# Initial cluster centres
centres = [
    (values[0], values[1]),
    (values[2], values[3]),
    (values[4], values[5])
]


# Euclidean distance squared
def distance_squared(p1, p2):
    return (p1[0] - p2[0])**2 + (p1[1] - p2[1])**2


# K-means algorithm
while True:
    clusters = [[], [], []]

    # Assign points to nearest cluster
    for point in data:
        distances = [distance_squared(point, centre) for centre in centres]
        min_index = distances.index(min(distances))
        clusters[min_index].append(point)

    # Compute new centres
    new_centres = []

    for cluster in clusters:
        if len(cluster) == 0:
            new_centres.append((0, 0))
        else:
            mean_x = sum(point[0] for point in cluster) / len(cluster)
            mean_y = sum(point[1] for point in cluster) / len(cluster)
            new_centres.append((mean_x, mean_y))

    # Check convergence
    if new_centres == centres:
        break

    centres = new_centres

# Compute sum-of-squares error
sse = 0

for i in range(3):
    for point in clusters[i]:
        sse += distance_squared(point, centres[i])

# Output rounded to 4 decimal places
print(f"{sse:.4f}")